spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lab_resourse_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
server.port=${PORT:8080}

# HikariCP Connection Pool

# Maximum number of connections in the pool
spring.datasource.hikari.maximum-pool-size=5

# Minimum number of idle connections in the pool
spring.datasource.hikari.minimum-idle=1

# Maximum time (30 seconds) to wait for a connection before throwing an exception.
spring.datasource.hikari.connection-timeout=30000

# Close connections that have been idle for 10 minutes.
spring.datasource.hikari.idle-timeout=600000

# Recreate connections after 30 minutes to avoid stale connections.
spring.datasource.hikari.max-lifetime=1800000

# Don't fail application startup immediately if the database
# isn't available. Retry in the background instead.
spring.datasource.hikari.initialization-fail-timeout=0

# Use 'update' to create missing tables and update schema / JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Don't run schema.sql automatically - run it manually
spring.sql.init.mode=never

logging.level.org.springframework.web=INFO

# Spring Boot
spring.main.lazy-initialization=true

# Logging
logging.level.root=INFO

#Email Configuration
spring.mail.host=smtp-relay.brevo.com
# port 587 to 2525
spring.mail.port=2525
spring.mail.username=${SPRING_MAIL_USERNAME:test@example.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:test}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


app.email.from=${APP_EMAIL_FROM:test@example.com}

# OTP Configuration
otp.expiration.minutes=5

#JWT Configuration

jwt.secret=${JWT_SECRET:aGVsbG8td29ybGQtd2VsY29tZS10by1qd3Qtc2VjcmV0LWtleQ==}

#30 days
jwt.expiration=2592000000